'use strict';

const MOCK_PRODUCTS = [
  {
    product_id: 1,
    product_name: 'Veg Biryani',
    description: 'Aromatic rice with veggies & spices.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'main course',
    price: 80,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 2,
    product_name: 'Chicken Biryani',
    description: 'Spiced chicken & basmati rice.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'main course',
    price: 120,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 3,
    product_name: 'Masala Dosa',
    description: 'Crispy dosa with potato masala.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'breakfast',
    price: 50,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 4,
    product_name: 'Idli Sambar',
    description: 'Soft idlis served with sambar.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'breakfast',
    price: 40,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 5,
    product_name: 'Paneer Butter Masala',
    description: 'Creamy tomato gravy with paneer.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'main course',
    price: 90,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 6,
    product_name: 'Veg Fried Rice',
    description: 'Wok-tossed rice with veggies.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'main course',
    price: 70,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 7,
    product_name: 'Chai',
    description: 'Hot milk tea.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'drinks',
    price: 15,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 8,
    product_name: 'Coffee',
    description: 'Strong filter coffee.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'drinks',
    price: 20,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 9,
    product_name: 'Samosa',
    description: 'Crispy snack with potato filling.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'snacks',
    price: 15,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
  {
    product_id: 10,
    product_name: 'Gulab Jamun',
    description: 'Sweet dessert in sugar syrup.',
    model_url: 'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
    texture_url: null,
    width: null,
    height: null,
    depth: null,
    category: 'desserts',
    price: 30,
    created_at: new Date('2026-01-01T00:00:00.000Z'),
  },
];

// In-memory scan counts – mutated by POST /api/qr/:qrCode/scan
const MOCK_QR_MAPPINGS = [
  { qr_id: 1,  qr_code: 'veg-biryani',         product_id: 1,  scan_count: 0 },
  { qr_id: 2,  qr_code: 'chicken-biryani',      product_id: 2,  scan_count: 0 },
  { qr_id: 3,  qr_code: 'masala-dosa',          product_id: 3,  scan_count: 0 },
  { qr_id: 4,  qr_code: 'idli-sambar',          product_id: 4,  scan_count: 0 },
  { qr_id: 5,  qr_code: 'paneer-butter-masala', product_id: 5,  scan_count: 0 },
  { qr_id: 6,  qr_code: 'veg-fried-rice',       product_id: 6,  scan_count: 0 },
  { qr_id: 7,  qr_code: 'chai',                 product_id: 7,  scan_count: 0 },
  { qr_id: 8,  qr_code: 'coffee',               product_id: 8,  scan_count: 0 },
  { qr_id: 9,  qr_code: 'samosa',               product_id: 9,  scan_count: 0 },
  { qr_id: 10, qr_code: 'gulab-jamun',          product_id: 10, scan_count: 0 },
];

module.exports = { MOCK_PRODUCTS, MOCK_QR_MAPPINGS };
